### ISSUE TITLE
Make dates comparable

### ISSUE THREAD

**Issue by KhashayarMirMS** [FatulM/shamsi_date#1]
It would be nice to be able to compare Jalali dates without converting them to DateTime objects or comparing their fields.

**Comment by FatulM** [comment]
I have implemented _Comparable_ on _Jalali_ and _Gregorian_ classes in version 0.5.1
Now you can compare them directly
@KhashayarMirMS

**Comment by FatulM** [comment]
I have also added comparison operators for them in version 0.5.2
@KhashayarMirMS
