### ISSUE TITLE
The method distanceTo isn't defined for type Jalali

### ISSUE THREAD

**Issue by tazik561** [FatulM/shamsi_date#11]
I have this jalali instance :
```
    jStartDate = jStartDate.withDay(1);
    jEndDate = jEndDate.withDay(1);
```
I want to find out how many days are between jStartDate and jEndDate ?
So in order to find out days I am using :
`    int distance = jStartDate.distanceTo(jEndDate);`

But I got: 'The method distanceTo isn't defined for type 'Jalali`

**Comment by FatulM** [comment]
Can you provide me with a complete example ?
And also please tell me your shamsi_date version
May be you are using an outdated version ?
Distance to is introduced in 0.14.1

**Comment by FatulM** [comment]
This is a weird error ☺️

**Comment by tazik561** [comment]
> Can you provide me with a complete example ?
> And also please tell me your shamsi_date version

I am using `  shamsi_date: ^0.9.1  ` 

This is my methods :

```
  Jalali jStartDate;
  Jalali jEndDate;
  void getJalaliDateSelected() {
      jStartDate = Jalali.now();
      jEndDate = Jalali.now();
    jStartDate = jStartDate.withDay(1);
    jEndDate = jEndDate.withDay(1);
    int distance = jStartDate.distance(jEndDate);

  }

```

My project not support null safety? How can i find distance in this version? Is it possible?

**Comment by FatulM** [comment]
```dart
import 'package:shamsi_date/shamsi_date.dart';

void main() {
  var a = Jalali(1390, 1, 10);
  var b = Jalali.now();

  a = a.withDay(1);
  b = b.withDay(1);

  print(a.distanceTo(b));
  print(b.distanceFrom(a));
  print(b ^ a);
}
```

this works fine ... i checked ...

**Comment by tazik561** [comment]
> ```dart
> import 'package:shamsi_date/shamsi_date.dart';
> 
> void main() {
>   var a = Jalali(1390, 1, 10);
>   var b = Jalali.now();
> 
>   a = a.withDay(1);
>   b = b.withDay(1);
> 
>   print(a.distanceTo(b));
>   print(b.distanceFrom(a));
>   print(b ^ a);
> }```
> 
> this works fine ... i checked ...
> ```

You are using `0.14.1` but I am using `^0.9.1 ` .In this version it is not possible to find days differences between two jalalis date?

**Comment by FatulM** [comment]
You can subtract their julianDayNumber

Like

a.julianDayNumber - b.julianDayNumber

For legacy vesions
