### ISSUE TITLE
bug in addMonths method

### ISSUE THREAD

**Issue by faridfr** [FatulM/shamsi_date#13]
https://github.com/FatulM/shamsi_date/blob/218ef76c2dd4e41e6af0c7d80224c095f48d1050/lib/src/jalali/jalali_date.dart#L258

<p dir="rtl">
این متد روز رو تغییر نمیده ، و مثلا اگر 31 شهریور باشیم میره به 31 مهر و خطا میخوره . ممنون میشم بررسی کنید
</p>

**Comment by FatulM** [comment]
سلام
دقیقا داکیمنتیشنش اشاره کردم همین مطلب رو. و هم توی ریدمی.
کار دیگه ای به ذهنم نمیرسه ... شما اگه پیشنهاد بهتری دارین بگین.
چون مثلا اگه منظورتون این بود که به جای یک ماه ۳۰ روز اضافه کنم که خوب ۳۰ روز خودتون با + یا متد اضافه کردن روز اضافه می کردین.
اگر هم که نه من از کجا بدونم که مثلا یک ماه بعد از ۳۱ شهریور منظورتون کی هست ؟ باید برم ۳۰ مهر یا مثلا ۱ آبان ؟ مشخص نیست دیگه.
توی ریدمی کامل بخونین یه سری توضیح دادم
باید بگین کاربردتون دقیق چیه تا راهنمایی کنم.
این جور موارد رو دو سری اپروچ من دیدم براش٫ یه سری مثل این لایبرری خطا میدن٫ یه سری سعی می کنن تصحیحش کنن٫ من خطا دادن رو ترجیح میدم. چون اولا جواب غیر قابل پیش بینی نامیده لایبرری ثانیا باعث میشه یوزر اون چیزی که می خواهد رو دقیق مشخص کنه و جلوی باج های لاجیکال رو می‌گیرد.

**Comment by faridfr** [comment]
@FatulM 
<p dir="rtl">
ممنون از پاسختون. حرف شما درسته و ما میتونیم توی پکیجمون راه حلی برای این قضیه پیدا کنیم<br>
ولی برای این چالش فکر میکنم باید یه ذره بیشتر توسعه اش بدیم و حالت های مختلف رو در نظر بگیریم<br>
مثلا فایل زیر رو ببینید <br>
https://github.com/briannesbitt/Carbon/blob/master/src/Carbon/Carbon.php<br>
و داخل این فایل addMonth رو جستجو کنید<br>
</p>

**Comment by FatulM** [comment]
من یه نگاه به کد پکیجتون انداختم ...
مثلا وقتی شما روز رو لازم ندارین حتی دستی دارین ۱ مینویسین توی استرینگ
توی ریدمی هم توضیح دادم فک کنم
```
j.withDay(1).addMonths(1)
```
می تونین بزنین
این کاملا سیف هست

**Comment by FatulM** [comment]
یه پیشنهاد دیگه هم این که
اگه فقط شمسی و میلادی رو ساپورت می کردین
می تونستین مستقیما از خود Jalai و Gregorian استفاده کنین، که ساب گلس Date هستن هر دو
نیازی به استرینگ کردن و ‌... نبود
این طوری سیف تر هم بود

**Comment by FatulM** [comment]
من یه نگاه به کد پکیجتون انداختم ...
مثلا وقتی شما روز رو لازم ندارین حتی دستی دارین ۱ مینویسین توی استرینگ
توی ریدمی هم توضیح دادم فک کنم
```
j.withDay(1).addMonths(1)
```
می تونین بزنین
این کاملا سیف هست

یه پیشنهاد دیگه هم این که
اگه فقط شمسی و میلادی رو ساپورت می کردین
می تونستین مستقیما از خود Jalai و Gregorian استفاده کنین، که ساب گلس Date هستن هر دو
نیازی به استرینگ کردن و ‌... نبود
این طوری سیف تر هم بود
این طوری کدتون هم خیلی کوتاه تر میشد
پرفورمنس هم بالا می‌رفت احتمالا


اون لایبرری php رو هم یه نگاه انداختم 
همون حالت دوم هست که گفتم تصحیح می‌کنه خودش، میشه یه سری متد با اجازه دادن اورفلو اضافه کرد تو شمسی دیت هم.
مثلا addMonthsSafe
مشابه مال اون
باید یه بررسی کنم سر فرصت ...

**Comment by faridfr** [comment]
@FatulM 
خیلی ممنون از وقتی که گذاشتید . حتما از پیشنهادی که دادید استفاده میکنیم

@HoseinHaqiqian
پیشنهاد امیررضا برای روز اول ماه بهتر از کاریه که الان میکنیم

**Comment by FatulM** [comment]
ممنون کلوز کردین
شرمنده من دوباره کدتون رو یه نگاه انداختم
به جای
`int.parse(date.formatter.y)`
می تونین خیلی راحت
`date.year`
بزنین 
تو ریدمی هم گفتم
خیلیا این اشتباه رو می کنن !
سلامت باشید انشاءالله
