### ISSUE TITLE
Month checking Issue

### ISSUE THREAD

**Issue by Mohammad-Hosein88** [FatulM/shamsi_date#15]
There was an error in Jalali formatter file which was an if statement checking if received month is treater than ml or not(ml being month length). months are 31 or 30 but it just accepted lower than this number meaning greatest month length was 30 so I got an error and check you code and found it out. I committed my change so it would be great if you accepted it ASAP because Im using it inside my project. Thanks in advance :)

**Comment by FatulM** [comment]
Hi,
I've read your issues and checked your pull requests.
First of all you have created two separate pull requests, please close one of them.
Second, I don't get your point and I think the code is correct ...
Can you please provide an example in case I have misunderstood you ?

**Comment by Mohammad-Hosein88** [comment]
Hey there
For example if the month is Tir (which has 31 days) and you try to set its day 31, it would give an error saying Jalali day out of range, also if you set the day 30 in Azar (which has 30 days) it would also give the same error

**Comment by FatulM** [comment]
In test file:
https://github.com/FatulM/shamsi_date/blob/master/test/shamsi_date_test.dart
There are examples for last day of a month:
like
https://github.com/FatulM/shamsi_date/blob/master/test/shamsi_date_test.dart#L347
which is
```dart
Jalali(1393, 1, 31);
```
contradictory to your issue.

please provide a complete reproducible example with error messages, outputs and etc.
