### ISSUE TITLE
is it possible get holidays

### ISSUE THREAD

**Issue by iranandroid** [FatulM/shamsi_date#18]
Hi, i wanna get holidays in week. is it possible calculate holidays?
thank you

**Comment by FatulM** [comment]
Hi,
By now this feature is not available,
If you have list of holidays in shamsi or miladi calendara,
You can create a map, and use it to find holidays

And also there is a problem
Several holidays of Iran are based on hijri calendar,
Which I don't think without using an internet connection you can get the exact hijri date,
So it is not possible to embed all holidays in this Library

And also there is another issue,
Which is that some holidays are changed (added) year by year ... Which it means that I should update the Library too often
