### ISSUE TITLE
Afghani Month Name

### ISSUE THREAD

**Issue by yasin1376** [FatulM/shamsi_date#25]
I hope you are doing so I have checked the package and it is awesome.

Great Job,

If you add the Afghani month name in this package it would be great.

**Comment by FatulM** [comment]
Hi,
Thanks.

Can you please give me the month names in Afghani ?

**Comment by FatulM** [comment]
And also the week day names if they are different from Iranian Farsi names ...

**Comment by FatulM** [comment]
the current names for Farsi are the following:

```dart
/// Jalali month names
static const List<String> _monthNames = [
  'فروردین',
  'اردیبهشت',
  'خرداد',
  'تیر',
  'مرداد',
  'شهریور',
  'مهر',
  'آبان',
  'آذر',
  'دی',
  'بهمن',
  'اسفند',
];

/// Jalali week day names
static const List<String> _weekDayNames = [
  'شنبه',
  'یک شنبه',
  'دو شنبه',
  'سه شنبه',
  'چهار شنبه',
  'پنج شنبه',
  'جمعه',
];
```

**Comment by yasin1376** [comment]
> Hi, Thanks.
> 
> Can you please give me the month names in Afghani ?

These are the Afghani month names: 

```
'حمل',
'ثور',
'جوزا',
'سرطان',
'اسد',
'سنبله',
'میزان',
'عقرب',
'قوس',
'جدی',
'دلو',
'حوت'
```

**Comment by yasin1376** [comment]
> And also the week day names if they are different from Iranian Farsi names ...

The Afghani week day names are the same with Iranian Farsi names.

**Comment by yasin1376** [comment]
@FatulM Please bring this changes soon that we can use in our new applications.

**Comment by FatulM** [comment]
Hi,
I've added Afghani month names in version `1.0.4`.
you can access them using `mNAf` getter in `JalaliFormatter`.
Please check readme for more information.
Thanks.
