### ISSUE TITLE
addMonth() make invalid date in some cases

### ISSUE THREAD

**Issue by NaarGes** [FatulM/shamsi_date#3]
addMonth() method just go to the next month on same day but in some cases there are no such a date, like next month of 31/6 which is 31/7 or previous month of 31/1 which is 31/12

**Comment by FatulM** [comment]
Hi,
This is a known issue, but I don't know how to solve it!

At present my project is to make some changes on the next release to enforce dates being valid. Then if you want to create an invalid date by using constructors or operators like addMonth,  it will throw exception. This way all of the dates are valid and it's the user's responsibility to catch exceptions or avoid it in the first place. I think this is the way that libraries like joda-time in Java handle this issue.

What is your opinion ?
@NaarGes

**Comment by NaarGes** [comment]
yes thank you, prevention of creating invalid dates is a good idea and it can be done by throwing an error.

**Comment by FatulM** [comment]
Hi,
I have fixed the issue in version 0.9.0.

Now ALL created date instances are valid. When you are creating a new date instance if think it can be invalid or become out of computable range you should surround code block with try-catch and capture `DateException`.

Is your problem solved ?
@NaarGes

**Comment by NaarGes** [comment]
I've handled this case manually

**Comment by FatulM** [comment]
> I've handled this case manually

Now in the 0.9.0 version you can soround your code block with try-catch instead of handling manually. Sorry for being so late in solving this issue, I didn't have time ...

I'll close this issue. If your problem is not solved feel free to reopen this issue or creating another one ...

@NaarGes
