### ISSUE TITLE
Diff 2 dates

### ISSUE THREAD

**Issue by mehrdad-shokri** [FatulM/shamsi_date#4]
Suppose I have 2 ``Jalali`` instances, how do I diff them in months?  I suppose converting them back to ``DateTime`` and using ``difference`` method won't work, because there's no correlation between Jalali and Gregorian month diffs.

**Comment by FatulM** [comment]
Hi,
You can use a simple method like this:

```dart
int diff(Jalali j1, Jalali j2) {
    return (j1.year - j2.year)*12 + (j1.month - j2.month);
}
```
