### ISSUE TITLE
How to access time data?

### ISSUE THREAD

**Issue by Hamidrezana** [FatulM/shamsi_date#5]
I want to show time next to date, e.g.: `1399/06/15 23:55`

How can I do it with this library?

I using MillisecondsEpoch.

**Comment by FatulM** [comment]
Hi,
You can't store time data in this library.

You should first convert your millisecond epoch to flutter's `DateTime` and store it for accessing hours and minutes. Then convert this `DateTime` object to `Jalali` and use it's formatter to format date data. Then combine formatted date data and time data (hour and minutes) from `DateTime` with each other.

Did I answer your question ?
@Hamidrezana

**Comment by Hamidrezana** [comment]
What I've done before is what you said.

I just wanted to know I can do it just with this library.

tnx
