### ISSUE TITLE
Why screenshots of calendar is not included in this package?

### ISSUE THREAD

**Issue by abaturyna** [FatulM/shamsi_date#6]

**Comment by FatulM** [comment]
Hi,
This is not a UI package! 😅
shamsi_date is an alternative for dart's DateTime providing support for persian dates.
If you have a Java background، This package is like JodaTime for Java which extends capabilities of it's original Date classes.

**Comment by FatulM** [comment]
If you want UI packages you can use packages that are built on top of shamsi_date, which is listed here:
https://pub.dev/packages?q=dependency%3Ashamsi_date

**Comment by FatulM** [comment]
If you have any other questions, feel free to reopen this issue or create an other ...
@abaturyna
